global cosplaySettings


% Module data
cosplaySettings=[];
cosplaySettings.moduleSeq5={};
cosplaySettings.moduleSeq3={};

cosplaySettings.moduleSeq5{1}='CGAATGCATCTAGATATCGGATCCCGGTCTCGATCC';
cosplaySettings.moduleSeq3{1}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTCATA';

cosplaySettings.moduleSeq5{2}='CGAATGCATCTAGATATCGGATCCCGGTCTCGTATG';
cosplaySettings.moduleSeq3{2}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTGTTC';

cosplaySettings.moduleSeq5{3}='CGAATGCATCTAGATATCGGATCCCGGTCTCGGAAC';
cosplaySettings.moduleSeq3{3}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTTGCGCCTCC';

cosplaySettings.moduleSeq5{4}='CGAATGCATCTAGATATCGGATCCCGGTCTCGCGCA';
cosplaySettings.moduleSeq3{4}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTCCTG';

cosplaySettings.moduleSeq5{5}='CGAATGCATCTAGATATCGGATCCCGGTCTCGCAGG';
cosplaySettings.moduleSeq3{5}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTTGCT';

cosplaySettings.moduleSeq5{6}='CGAATGCATCTAGATATCGGATCCCGGTCTCGAGCA';
cosplaySettings.moduleSeq3{6}='GCAGGCCTCTGCAGTCGACGGGCCCGGTCTCTATGG';
